config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'main' => 'pages#main'
  get 'about' => 'pages#about'
  get 'happy' => 'pages#happy'
  get 'our_contacts' => 'pages#our_contacts'
  get '/' => 'pages#main'
  post '/' => 'contacts#create'


  resources :contacts do
	   resources :comments
  end
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :contact
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
   protect_from_forgery prepend: true
   before_action :configure_permitted_parameters, if: :devise_controller?

   private
   def configure_permitted_parameters
     #devise_parameter_sanitizer.for(:sign_up) << :username
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
     #devise_parameter_sanitizer.for(:sign_in) << :username
     #devise_parameter_sanitizer.for(:account_update) << :username
   end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
	  @contact=Contact.find(params[:contact_id])
    @contact.comments.create(comment_params)
    redirect_to contact_path(@contact)
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
     @contact=Contact.find(params[:contact_id])
    redirect_to contact_path(@contact)
  end


  private
  def comment_params
  	params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  layout "contacts"
  skip_before_action  :verify_authenticity_token

  before_action :authenticate_user!, except: [:create]

  def new
  end

  def create
    @contact=Contact.new(contact_params)
    if @contact.valid?
      @contact.save
      @message="Вы записаны!!!"
    else
      @message="Заполните все строки формы!"
    end

    redirect_back(fallback_location: "main")
  #  render action: 'about'

  end

  def index
    @contacts=Contact.all
  end

  def show
    @contact=Contact.find(params[:id])
  end

  def destroy
  	@contact=Contact.find(params[:id])
  	@contact.destroy
  	  redirect_to contacts_path
  end

private
  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end

  def about
  end

  def our_contacts
  end

  def happy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h2>Спасибо! Ваши данные занесены в базу данных. Мы обязательно с вами свяжемся.</h2>

app/views/contacts/index.html.erb
<h1>Список контактов:</h1>

<% @contacts.each do |contact| %>
	<h2>
		<%= contact.name %>
	</h2>
	<p>
			<%= contact.phone %>
	</p>
	<p>
			<%= contact.email %>
	</p>

	<p>
		<%= contact.message %>
	</p>

	<p>
		Всего <%= contact.comments.size %> комментариев.
	</p>

	<p>
		<%= link_to 'Показать', contact_path(contact) %> |
		<%= link_to 'Удалить', contact_path(contact), method: :delete, data:{ confirm: "Вы уверены?" } %>
	<p/>
	<hr />
<% end %>

app/views/contacts/new.html.erb
<h2>Ошибка!!!</h2>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>
<h3> Телефон:  <%= @contact.phone %>  Email: <%= @contact.email %> </h3>
<p>
  <%= @contact.message %>
</p>

<h2>Комментарии:</h2>
<% @contact.comments.each do |comment| %>
  <p>
    <i><%= comment.author %> сказал:</i><br />
    <%= comment.body %>
    <%= link_to "Удалить", contact_comment_path(@contact, comment), :method => :delete, data:{ confirm: "Вы уверены?" } %>
  </p>

<% end %>

<h2>Добавить комментрий</h2>

<p>
<%= form_for([@contact, @contact.comments.build]) do |f| %>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit("Добавить") %>
  </p>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faberlic Черкассы</title>
    <!--<%= csrf_meta_tags %>-->

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <!-- Bootstrap -->
    <!--<link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav>
      <div class="container">
        <div class="row">
          <div class="navbar-header">
            <button class="navbar-toggle collapsed menu_btn" data-toggle="collapse" data-target="#top_menu">
              <span class="glyphicon glyphicon-menu-hamburger"></span>
            </button>

              <%= link_to image_tag("logo.png", alt: "Logo" ), "/main" %>

          </div>

          <div class="collapse navbar-collapse navbar-right" id="top_menu">
            <ul class="menu">
              <li><a href="/main">Главная</a></li>
              <li><a href="/happy">Удача</a></li>
              <li><a href="/about">О нас</a></li>
              <li><a href="/our_contacts">Контакты</a></li>
            </ul>
          </div>
        </div>
        <div class="top_line"></div>
      </div>
    </nav>

  </header>
  <%if @message then %>
          <div>
            <h2><%=@message%></h2>
          </div>
      <% end %>

      <div class="alert alert-success hidden" id="success-alert">
        <h2>Успех</h2>
        <div>Ваши данные были успешно отправлены.</div>
      </div>

    <%= yield %>

    <footer>
    		<div class="main_footer">
    			<div class="container">
    				<div class="row">

    					<div class="col-md-4 col-sm-6">
    						<div class="footer_item">
    							<h5>Faberlic</h5>
    							<p>Мы всегда рады вас видеть<br></p>
    						</div>
    					</div>

    					<div class="col-md-4 col-sm-6">
    						<div class="footer_item">
    							<h5>Наши контакты</h5>
    							<button class="soc_btn_white">
    								<i class="fa fa-facebook"></i>
    							</button>
    							<button class="soc_btn_white">
    								<i class="fa fa-twitter"></i>
    							</button>
    							<button class="soc_btn_white">
    								<i class="fa fa-linkedin-square"></i>
    							</button>
    						</div>
    					</div>

    					<div class="col-md-4 hidden-xs hidden-sm">
    						<div class="footer_item">
    							<h5>Faberlic</h5>
    							<p>Мы всегда рды вас видеть<br></p>
    						</div>
    					</div>

    				</div>

    			</div>
    		</div>

    		<div class="copyright_block">
    			<div class="container">
    				<div class="row">
    					<div class="col-md-4 col-md-offset-4">
    						<div class="copy_txt">
                  <h4>Faberlic - в Черкссах</h4>
                  <p>Подписаться</p>
                  <a href="http://faberlic.com/register?sposor=26414361" class="my_btn btn_md">Faberlic</a>
    						</div>
    					</div>
    				</div>
    			</div>
    		</div>

    		<button class="call_btn" data-toggle="modal" data-target="#dlModal">
    			<span class="glyphicon glyphicon-earphone"></span>
    		</button>
    </footer>

<!-- <div class="modal fade" id="dlModal1">
 <div class="modal-dialog">
   <div class="modal-content">

     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title">Ваши личные данные</h4>
     </div>

     <div class="modal-body">
       <form action="/" method="post" id="dlForm1">
         <input type="text" class="form-control" placeholder="Ваше имя" name="contact[name]">
         <input type="text" class="form-control" placeholder="Ваш телефон" name="contact[phone]">
         <input type="email" class="form-control" placeholder="Ваш E-Mail" name="contact[email]">
         <textarea class="form-control" placeholder="Сообщение" rows="3" name="contact[message]"></textarea>
         <input id="save" type="submit" value="Отослать" class="my_btn btn_md btn-block">
       </form>
     </div>
   </div>
 </div>
</div> -->

<!-- Модальное окно -->
<div class="modal fade" id="dlModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Заголовок модального окна -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="myModalLabel">Ваши личные данные</h4>
      </div>
      <!-- Основная часть модального окна, содержащая форму для регистрации -->
    <div class="modal-body">
        <!-- Форма для регистрации -->
  	<form action="/" method="post" role="form" class="form-horizontal" id="submit_form">
	  <!-- Блок для ввода имени -->
	  <div class="form-group has-feedback">
	    <label for="name" class="control-label col-xs-3">Имя:</label>
	    <div class="col-xs-6">
	      <div class="input-group">
	        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
	        <input type="text" class="form-control" required="required" name="contact[name]" pattern="[A-Za-zА-Яа-я]{3,}">
	      </div>
	      <span class="glyphicon form-control-feedback"></span>
	    </div>
	  </div>
    <!-- Блок для ввода телефона -->
    <div class="form-group has-feedback">
	    <label for="phone" class="control-label col-xs-3">Телефон:</label>
	    <div class="col-xs-6">
	      <div class="input-group">
	        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
	        <input type="text" class="form-control" required="required" name="contact[phone]">
	      </div>
	      <span class="glyphicon form-control-feedback"></span>
	    </div>
	  </div>

	  <!-- Блок для ввода email -->
	  <div class="form-group has-feedback">
	    <label for="email" class="control-label col-xs-3">Email:</label>
	    <div class="col-xs-6">
	      <div class="input-group">
	        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
	        <input type="email" class="form-control" required="required" name="contact[email]">
	      </div>
	      <span class="glyphicon form-control-feedback"></span>
	    </div>
	  </div>
          <!-- Конец блока для ввода email-->
     <textarea class="form-control" placeholder="Сообщение" rows="6" name="contact[message]"></textarea>
    <!-- <input id="save" type="submit" value="Отослать" class="my_btn btn_md btn-block"> -->
    </form>
  </div>
      <!-- Нижняя часть модального окна -->
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
        <button id="save" type="button" class="btn btn-primary">Отправить</button>
      </div>
    </div>
  </div>
</div>

<script>
$(function() {
  //push button with id="save"
  $('#save').click(function() {
    var formValid = true;
    //finde all elements input
    $('input').each(function() {
    //finde parents, which have class .form-group, for setting success/error
    var formGroup = $(this).parents('.form-group');
    //finde glyphicon, wich is showing success or error
    var glyphicon = formGroup.find('.form-control-feedback');
    //or validatin use HTML5 function checkValidity
    if (this.checkValidity()) {
      //add to formGroup class .has-success, delete has-error
      formGroup.addClass('has-success').removeClass('has-error');
      //add to glyphicon class glyphicon-ok, delete glyphicon-remove
      glyphicon.addClass('glyphicon-ok').removeClass('glyphicon-remove');
    } else {
      //add to formGroup csass .has-error, delete .has-success
      formGroup.addClass('has-error').removeClass('has-success');
      //add to glyphicon class glyphicon-remove, delete glyphicon-ok
      glyphicon.addClass('glyphicon-remove').removeClass('glyphicon-ok');
      formValid = false;
    }
  });
  //if form is valid
  if (formValid) {
    //hide modal window
    $('#dlModal').modal('hide');
    //show success alert
    $('#success-alert').removeClass('hidden');
    //send post request
    $('#submit_form').submit();
  }
});
});
</script>

</body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Контакты</title>
  </head>
  <body>

    <%= link_to image_tag("logo.png", alt: "Logo" ), "/main" %><hr/>
    <% if user_signed_in? %>
      <%= current_user.email %> | <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
    <% end %>

  <%= yield %>
</body>
</html>

app/views/layouts/contacts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Контакты</title>
  </head>
  <body>

    <%= link_to image_tag("logo.png", alt: "Logo" ), "/main" %><hr/>
    <% if user_signed_in? %>
      <%= current_user.email %> | <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
    <% end %>

  <%= yield %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h2>Аутентификация</h2>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Мы находимся по адресу ул.Смелянская, 63</h1>

<section class="works_s">
<div class="container-fluid">
  <div class="row">

    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <!--<img src="img/work-1.jpg" class="img-responsive" alt="workItem">-->
        <%= image_tag("work-1.jpg", class: "img-responsive", alt: "work-1") %>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-2.jpg", class: "img-responsive", alt: "work-2") %>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-3.jpg", class: "img-responsive", alt: "work-3") %>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-4.jpg", class: "img-responsive", alt: "work-4") %>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-5.jpg", class: "img-responsive", alt: "work-5") %>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-6.jpg", class: "img-responsive", alt: "work-6") %>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-7.jpg", class: "img-responsive", alt: "work-7") %>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 p0">
      <div class="work_block">
        <div class="image_wrap">
          <div class="work_descr">
            <h4>PROJECT NAME</h4>
            <p>some description</p>
          </div>
        </div>
        <%= image_tag("work-8.jpg", class: "img-responsive", alt: "work-8") %>
      </div>
    </div>
  </div>
</div>
</section>

app/views/pages/happy.html.erb
<!DOCTYPE html>
<h1>Удача всегда с Вами!!!</h1>
<div class="team_item">

   <%= video_tag("video1.mp4", size: "640x480", controls: true) %>

</div>

app/views/pages/main.html.erb
<html>
	<head>
		<title>Faberlic Черкассы</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<!-- Bootstrap -->
	<!--	<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

			<link rel="stylesheet" href="css/main.css" />
			<link rel="stylesheet" href="css/media.css" />
			<link rel="stylesheet" href="css/fonts.css" />-->
	</head>
<body>
<section class="team_s">
  <h1><center>Faberlic выпускает разнообразную продукцию</center></h1><br>
   <div class="container">
     <div class="row">

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
          <%= image_tag("Косметика.png", class: "img-responsive", alt: "Косметика" ) %>
           <!--<img src="img/Косметика.png" class="img-responsive" alt="teamMember">-->
           <h4><center>Косметика</center></h4>
           <p>Декоративная косметика пряямо из Франции</p>
         </div>
       </div>

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
           <%= image_tag("Парфюмерия.png", class: "img-responsive", alt: "Парфюмерия") %>
           <h4>Парфюмерия</h4>
           <p>Оригинальная парфюмерия от французского производителя</p>
         </div>
       </div>

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
           <%= image_tag("Здоровье.png", class: "img-responsive", alt: "Здоровье") %>
           <h4>Здоровье</h4>
           <p>Здоровье - Самое дорогое, что у нас есть. Фирма предлагает широкий выбор товаров.</p>
         </div>
       </div>

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
           <%= image_tag("Гигиена.png", class: "img-responsive", alt: "Гигиена") %>
           <h4>Гигиена</h4>
           <p>Широкий выбор товаров для индивидуальной гигиены</p>

         </div>
       </div>

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
           <%= image_tag("Посуда.png", class: "img-responsive", alt: "Посуда") %>
           <h4>Посуда</h4>
           <p>Оригинальная и разнообразная посуда</p>
         </div>
       </div>

       <div class="col-md-2 col-sm-4">
         <div class="team_item">
           <%= image_tag("Одежда.png", class: "img-responsive", alt: "Одежда") %>
           <h4>Одежда</h4>
           <p>Современная удобная одежда на все случаи жизни, погоду и возраст</p>
         </div>
       </div>

     </div>
   </div>
 </section>

</body>
</html>

app/views/pages/our_contacts.html.erb
<h1>Как с нами связаться</h1>
<h2>Наши телефоны:</h2>
<p>Городской: 56-44-53</p>

<div class="container">
  <div class="row">

    <div class="col-md-6 col-sm-8">
      <div class="team_item">
       <%= image_tag("Sm_63.png", class: "img-responsive", alt: "Sm_63" ) %>
        <h4>Здесь нас можно найти.</h4>
      </div>
    </div>

  </div>
</div>